name: Auto-Tag Release

on:
  push:
    branches:
      - main

jobs:
  release_new_tag:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v1"
      - name: Read VERSION file
        id: getversion
        run: echo "::set-output name=version::$(egrep '^version':' [0-9.]+' pubspec.yaml | awk '{print $2}')"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: v${{ steps.getversion.outputs.version }}
          prerelease: false