name: Auto-Tag Release

on:
  push:
    branches:
      - main
    paths:
      - 'pubspec.yaml'

jobs:
  release_new_tag:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v1"
      - name: Get version from file
        id: getfileversion
        run: echo "::set-output name=fileversion::$(cat version)"
      - name: Get version from pubspec.ysml
        id: getpubversion
        run: echo "::set-output name=pubversion::$(egrep '^version':' [0-9.]+' pubspec.yaml | awk '{print $2}')"
      - name: Release new version
        id: release
        if: steps.getpubversion.outputs.pubversion != steps.getfileversion.outputs.fileversion
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.getpubversion.outputs.pubversion }}
          prerelease: false
      - name: Increase file version
        if: steps.release.outputs.exit_code == 0
        uses: "DamianReeves/write-file-action@v1.0"
        with:
          path: version
          contents: |
            ${{steps.getversion.outputs.pubversion}}
          write-mode: overwrite
      - run: git config --local user.email "action@github.com"
      - run: git config --local user.name "GitHub Action"
      - run: git add version
      - run: git commit -m "bump version"
      - run: "git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}