name: Automatic Release

on:
  push:
    branches:
      - main
    paths:
      - 'pubspec.yaml' # Only run the workflow if pubspec.yaml file has changes

jobs:
  release_new_tag:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
      - name: Get version from file
        id: getfileversion
        run: echo "::set-output name=fileversion::$(cat version)"
      - name: Get version from pubspec.ysml
        id: getpubversion
        run: echo "::set-output name=pubversion::$(egrep '^version':' [0-9.]+' pubspec.yaml | awk '{print $2}')"
      - name: Release new version
        id: release
        if: steps.getpubversion.outputs.pubversion != steps.getfileversion.outputs.fileversion
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.getpubversion.outputs.pubversion }}
          prerelease: false
      - name: Increase file version
        id: increasefileversion
        if: steps.release.outputs.exit_code == 0
        uses: "DamianReeves/write-file-action@v1.0"
        with:
          path: version
          contents: |
            ${{ steps.getpubversion.outputs.pubversion }}
          write-mode: overwrite # Automatically create the file or overwrite it if needed
      - name: Commit version file
        id: commitversionfile
        if: steps.increasefileversion.outputs.exit_code == 0
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add version
          git commit -m "Bump version"
          git push