name: Automatic Release

on:
  push:
    branches:
      - main
    paths:
      - 'version' # Only run the workflow if version file has changes


jobs:
  release_new_tag:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
      - name: Get version from file
        id: getfileversion
        run: echo "::set-output name=fileversion::$(cat version)"
      - name: Release new version
        id: release
        if: steps.getpubversion.outputs.pubversion != steps.getfileversion.outputs.fileversion
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.getfileversion.outputs.fileversion }}
          prerelease: false